[package]
name = "wire-keys"
edition.workspace = true
version.workspace = true

[dependencies]
wire-core = { path = "../core" }
wire-key-agent = { path = "../key_agent" }
serde.workspace = true
tokio.workspace = true
im = { workspace = true }
sha2 = { workspace = true }
either = "1.15.0"
secrecy.workspace = true

[lints]
workspace = true
