---
name: Set up Nix
description: |
  Sets up the Nix environment for wire, removing unnecessary bloat and installing Nix along with proper
  substituters being set
runs:
  using: "composite"
  steps:
    - name: Generate nix.conf
      shell: bash
      id: config
      run: |
        {
          echo 'config<<EOF'

          echo "system-features = nixos-test benchmark big-parallel kvm"

          echo EOF
        } >> "$GITHUB_OUTPUT"
    - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: ${{ steps.config.outputs.config }}
    - name: Sanity check nix.conf
      if: ${{ runner.debug == '1' }}
      shell: bash
      run: cat /etc/nix/nix.conf
    - uses: Mic92/niks3-action@12d3e320b2a99b7938f9634bd337cd9fec104609
      with:
        server-url: https://niks3.forall.systems
