[package]
name = "wire-plan"
edition.workspace = true
version.workspace = true

[dependencies]
wire-core = { path = "../core" }
wire-keys = { path = "../keys" }
wire-execute = { path = "../execute" }
im = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
enum_dispatch = { workspace = true }

[lints]
workspace = true
