# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: "Build"
on:
  pull_request:
  push:
jobs:
  pre-job:
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@04a1aebece824b56e6ad6a401d015479cd1c50b3
        with:
          concurrent_skipping: "same_content_newer"
          cancel_others: "true"
  find-jobs:
    runs-on: ubuntu-latest
    needs: pre-job
    permissions:
      contents: read
    if: needs.pre-job.outputs.should_skip != 'true'
    outputs:
      packages: ${{ steps.x86_64.outputs.packages }}
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - name: Find package jobs
        id: x86_64
        run: |
          echo "packages=$(nix eval .#hydraJobs.packages.x86_64-linux \
            --apply builtins.attrNames --json)" >> "$GITHUB_OUTPUT"
  build-key-agent-aarch64:
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
    needs: pre-job
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - name: Build
        run: nix build -L --print-out-paths .#packages.aarch64-linux.agent
  build-key-agent-x86_64:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: pre-job
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - name: Build
        run: nix build -L --print-out-paths .#packages.x86_64-linux.agent
  build:
    runs-on: ${{ matrix.arch.runner }}
    needs:
      - find-jobs
      - build-key-agent-x86_64
      - build-key-agent-aarch64
    permissions:
      id-token: write
    strategy:
      matrix:
        package: ${{ fromJSON(needs.find-jobs.outputs.packages) }}
        arch:
          - id: x86_64-linux
            runner: ubuntu-latest
          # disabled arm building,
          # currently handled by cachix and for development purposes i only use
          # x86_64
          #
          # - id: aarch64-linux
          #   runner: blacksmith-8vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - name: Build
        run: |
          nix build -L --print-out-paths \
            .#hydraJobs.packages."${ARCH}"."${MATRIX_PACKAGE}"
        env:
          MATRIX_PACKAGE: ${{ matrix.package }}
          ARCH: ${{ matrix.arch.id }}
