---
name: "Pages"
on:
  push:
    branches:
      - stable
      - trunk
  workflow_dispatch:
jobs:
  pre-job:
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@04a1aebece824b56e6ad6a401d015479cd1c50b3
  deploy:
    runs-on: ubuntu-latest
    permissions: {}
    environment:
      name: production
      url: https://wire.forall.systems/
    if: github.actor != 'dependabot[bot]' && needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - run: nix build .#docs
        if: github.ref == 'refs/heads/stable'
      - run: nix build .#docs-unstable
        if: github.ref != 'refs/heads/stable'
      - name: Deploy to Cloudflare Pages
        id: deployment
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./result/ --project-name wire-docs
