---
name: "Test"
on:
  pull_request:
  push:
jobs:
  pre-job:
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@04a1aebece824b56e6ad6a401d015479cd1c50b3
        with:
          concurrent_skipping: "same_content_newer"
          cancel_others: "true"
  test:
    runs-on: ubuntu-latest
    needs: pre-job
    permissions:
      contents: read
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
      - name: Build Tests
        run: nix build .#cargo-tests -L -vv
      - name: Cargo Tests
        run: |
          nix develop \
            --print-build-logs \
            -v \
            --command result/bin/run-tests
